# Generated by Django 5.2.12 on 2026-03-06 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(db_index=True, help_text="Tak list name , can't be empty and have 120 length size ", max_length=120, verbose_name='Nome da lista de tarefas')),
                ('description', models.CharField(blank=True, help_text='Task list description , can be empty and have 180 length size', max_length=180, verbose_name='Descrição da lista de terefas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('user', models.ForeignKey(help_text='user onwer of taks list', on_delete=django.db.models.deletion.CASCADE, related_name='tasklists', to=settings.AUTH_USER_MODEL, verbose_name='Dono da lista de tarefas')),
            ],
            options={
                'verbose_name': 'Lista de tarefas',
                'verbose_name_plural': 'Listas de tarefas',
                'db_table': 'task_list',
                'ordering': ['-created_at'],
            },
        ),
    ]
