# Generated by Django 5.2.12 on 2026-03-06 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='name',
            field=models.CharField(db_index=True, help_text="Task list name , can't be empty and have 120 length size ", max_length=120, verbose_name='Nome da lista de tarefas'),
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(db_index=True, help_text="Task title , can't be empty and have 120 length size ", max_length=120, verbose_name='Titulo da tarefa')),
                ('description', models.CharField(blank=True, help_text='Task description , can be empty and have 180 length size', max_length=180, verbose_name='Descrição da terefas')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluida')], default='pending', help_text='Task status , can be pending, in_progress, completed', max_length=20, verbose_name='Status da tarefa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('task_list', models.ForeignKey(help_text='task list which item belong to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.tasklist', verbose_name='Lista de tarefas a qual a tarefa pertence')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'db_table': 'task_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
