# Generated by Django 5.2.12 on 2026-03-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasklist_name_taskitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='content',
            field=models.TextField(blank=True, help_text='Task content , can be empty', null=True, verbose_name='Conteúdo da tarefa'),
        ),
    ]
