FROM python:3.11-slim

WORKDIR /usr/app/

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY ./backend/requirements/ ./requirements/

RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r ./requirements/prod.txt

COPY ./backend/ .

COPY ./scripts/api/entrypoint.sh ./entrypoint.sh

RUN  chmod +x ./entrypoint.sh

EXPOSE 8000

ENTRYPOINT [ "./entrypoint.sh" ]
